package text2;

public class ExceptionCatch {
	public static void main(String[] args) {
//		ExceptionSample sample = new ExceptionSample();
//		sample.method();
//		try(Scanner scanner = new Scanner(System.in)){
//			System.out.println("数値を入力");
//			int input = scanner.nextInt();
//			// scanner.close(); 今回は書く必要なし
//		} catch (Exception e) {
//			System.out.println("数値以外はだめ!");
//			//e.printStackTrace();
//		}
		System.out.println(); // 改行コード付き
		System.out.print("a"); // 改行なし
		System.out.print("b"); // 改行なし
//		try {
//			sample.method();
//			System.out.println("例外発生しなかった");
//		} catch (ArrayIndexOutOfBoundsException e) {
//			System.out.println("配列要素数がおかしいです");
//		}
	}
}
